// <auto-generated />
using System;
using Geodesic.App.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Geodesic.App.DataLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251210212724_AddSetupRunIdToWorkspaces")]
    partial class AddSetupRunIdToWorkspaces
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.AITeam", b =>
                {
                    b.Property<Guid>("AITeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ai_team_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("AITeamId")
                        .HasName("pk_ai_teams");

                    b.HasIndex("WorkspaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_ai_teams_workspace_id");

                    b.ToTable("ai_teams", "app");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.AITeamMember", b =>
                {
                    b.Property<Guid>("AITeamMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ai_team_member_id");

                    b.Property<Guid>("AITeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_team_id");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_id");

                    b.Property<string>("CommunicationStyle")
                        .HasColumnType("text")
                        .HasColumnName("communication_style");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string[]>("Expertise")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("expertise")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<int?>("MaxTokens")
                        .HasColumnType("integer")
                        .HasColumnName("max_tokens");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("system_prompt")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("numeric")
                        .HasColumnName("temperature");

                    b.Property<string[]>("Tools")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("tools")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("AITeamMemberId")
                        .HasName("pk_ai_team_members");

                    b.HasIndex("AITeamId", "AgentId")
                        .IsUnique()
                        .HasDatabaseName("ix_ai_team_members_ai_team_id_agent_id");

                    b.ToTable("ai_team_members", "app");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.AnswerableQuestion", b =>
                {
                    b.Property<Guid>("AnswerableQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("answerable_question_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<string[]>("RequiredVariables")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("required_variables")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string>("ResultPlaybook")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result_playbook");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("AnswerableQuestionId")
                        .HasName("pk_answerable_questions");

                    b.ToTable("answerable_questions", "app");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.Feedback", b =>
                {
                    b.Property<Guid>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("feedback_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<bool>("Applied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("applied");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<Guid?>("FeedbackRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("feedback_request_id");

                    b.Property<string>("FeedbackText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feedback_text");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("SubtaskId")
                        .HasColumnType("text")
                        .HasColumnName("subtask_id");

                    b.Property<string>("Target")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("target")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("TaskId")
                        .HasColumnType("text")
                        .HasColumnName("task_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("now()");

                    b.HasKey("FeedbackId")
                        .HasName("pk_feedbacks");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_feedbacks_run_id");

                    b.ToTable("feedbacks", "app");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.FeedbackRequest", b =>
                {
                    b.Property<Guid>("FeedbackRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("feedback_request_id");

                    b.Property<string>("Checkpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("checkpoint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_resolved");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string[]>("Options")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("options")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("TaskId")
                        .HasColumnType("text")
                        .HasColumnName("task_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TimeoutSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(300)
                        .HasColumnName("timeout_seconds");

                    b.HasKey("FeedbackRequestId")
                        .HasName("pk_feedback_requests");

                    b.HasIndex("RunId", "IsResolved")
                        .HasDatabaseName("ix_feedback_requests_run_id_is_resolved");

                    b.ToTable("feedback_requests", "app");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.Insight", b =>
                {
                    b.Property<Guid>("InsightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("insight_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("EvidenceRefs")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence_refs")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string[]>("RelatedGraphIds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("related_graph_ids")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("InsightId")
                        .HasName("pk_insights");

                    b.ToTable("insights", "app");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.OverlayChangeset", b =>
                {
                    b.Property<Guid>("ChangesetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("changeset_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("ChangesetId")
                        .HasName("pk_overlay_changesets");

                    b.ToTable("overlay_changesets", "app");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.OverlayEdgePatch", b =>
                {
                    b.Property<Guid>("ChangesetId")
                        .HasColumnType("uuid")
                        .HasColumnName("changeset_id");

                    b.Property<string>("GraphEdgeId")
                        .HasColumnType("text")
                        .HasColumnName("graph_edge_id");

                    b.Property<string>("Op")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("upsert")
                        .HasColumnName("op");

                    b.Property<string>("Patch")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("patch")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.HasKey("ChangesetId", "GraphEdgeId")
                        .HasName("pk_overlay_edge_patch");

                    b.ToTable("overlay_edge_patch", "app");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.OverlayNodePatch", b =>
                {
                    b.Property<Guid>("ChangesetId")
                        .HasColumnType("uuid")
                        .HasColumnName("changeset_id");

                    b.Property<string>("GraphNodeId")
                        .HasColumnType("text")
                        .HasColumnName("graph_node_id");

                    b.Property<string>("Op")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("upsert")
                        .HasColumnName("op");

                    b.Property<string>("Patch")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("patch")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.HasKey("ChangesetId", "GraphNodeId")
                        .HasName("pk_overlay_node_patch");

                    b.ToTable("overlay_node_patch", "app");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.Role", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("RoleName")
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("TenantId", "RoleName")
                        .HasName("pk_roles");

                    b.ToTable("roles", "app");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.Scenario", b =>
                {
                    b.Property<Guid>("ScenarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("scenario_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("HeaderText")
                        .HasColumnType("text")
                        .HasColumnName("header_text");

                    b.Property<string>("MainText")
                        .HasColumnType("text")
                        .HasColumnName("main_text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("RelatedChangesetId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_changeset_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("ScenarioId")
                        .HasName("pk_scenarios");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_scenarios_workspace_id_name");

                    b.ToTable("scenarios", "app");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.ScenarioMetric", b =>
                {
                    b.Property<Guid>("ScenarioMetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("scenario_metric_id");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("MainText")
                        .HasColumnType("text")
                        .HasColumnName("main_text");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("scenario_id");

                    b.Property<string>("SecondaryText")
                        .HasColumnType("text")
                        .HasColumnName("secondary_text");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("ScenarioMetricId")
                        .HasName("pk_scenario_metrics");

                    b.ToTable("scenario_metrics", "app");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.ScenarioRun", b =>
                {
                    b.Property<Guid>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("ArtifactsUri")
                        .HasColumnType("text")
                        .HasColumnName("artifacts_uri");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("engine");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Inputs")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("inputs");

                    b.Property<string>("Outputs")
                        .HasColumnType("text")
                        .HasColumnName("outputs");

                    b.Property<string>("Prompt")
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.Property<Guid?>("ScenarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("scenario_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("queued")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("RunId")
                        .HasName("pk_scenario_runs");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_scenario_runs_workspace_id");

                    b.ToTable("scenario_runs", "app");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.ScenarioRunLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LogId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("LogId")
                        .HasName("pk_scenario_run_logs");

                    b.ToTable("scenario_run_logs", "app");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.ScratchpadAttachment", b =>
                {
                    b.Property<Guid>("ScratchpadAttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("scratchpad_attachment_id");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FileType")
                        .HasColumnType("text")
                        .HasColumnName("file_type");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Uri")
                        .HasColumnType("text")
                        .HasColumnName("uri");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("ScratchpadAttachmentId")
                        .HasName("pk_scratchpad_attachments");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_scratchpad_attachments_workspace_id");

                    b.ToTable("scratchpad_attachments", "app");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.ScratchpadNote", b =>
                {
                    b.Property<Guid>("ScratchpadNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("scratchpad_note_id");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("ScratchpadNoteId")
                        .HasName("pk_scratchpad_notes");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_scratchpad_notes_workspace_id");

                    b.ToTable("scratchpad_notes", "app");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.SemanticEntity", b =>
                {
                    b.Property<Guid>("SemanticEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("semantic_entity_id");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NodeLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("node_label");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("SemanticEntityId")
                        .HasName("pk_semantic_entities");

                    b.HasIndex("TenantId", "NodeLabel", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_semantic_entities_tenant_id_node_label_version");

                    b.ToTable("semantic_entities", "app");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.SemanticField", b =>
                {
                    b.Property<Guid>("SemanticFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("semantic_field_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("SemanticEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("semantic_entity_id");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("SemanticFieldId")
                        .HasName("pk_semantic_fields");

                    b.HasIndex("SemanticEntityId")
                        .HasDatabaseName("ix_semantic_fields_semantic_entity_id");

                    b.HasIndex("SemanticEntityId", "Name", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_semantic_fields_semantic_entity_id_name_version");

                    b.ToTable("semantic_fields", "app");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("us")
                        .HasColumnName("region");

                    b.HasKey("TenantId")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", "app");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<string>("Preferences")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("preferences")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_id_email");

                    b.HasIndex("TenantId", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_id_subject");

                    b.ToTable("users", "app");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleName")
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.HasKey("UserId", "RoleName")
                        .HasName("pk_user_roles");

                    b.ToTable("user_roles", "app");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.Workspace", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<DateTimeOffset?>("BaseSnapshotTs")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("base_snapshot_ts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Intent")
                        .HasColumnType("text")
                        .HasColumnName("intent");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<Guid?>("SetupRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("setup_run_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("private")
                        .HasColumnName("visibility");

                    b.HasKey("WorkspaceId")
                        .HasName("pk_workspaces");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_workspaces_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_workspaces_tenant_id_name");

                    b.ToTable("workspaces", "app");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.WorkspaceAnalysis", b =>
                {
                    b.Property<Guid>("WorkspaceAnalysisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_analysis_id");

                    b.Property<string>("BodyText")
                        .HasColumnType("text")
                        .HasColumnName("body_text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("TitleText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_text");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("WorkspaceAnalysisId")
                        .HasName("pk_workspace_analyses");

                    b.ToTable("workspace_analyses", "app");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.WorkspaceAnalysisMetric", b =>
                {
                    b.Property<Guid>("WorkspaceAnalysisMetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_analysis_metric_id");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("MainText")
                        .HasColumnType("text")
                        .HasColumnName("main_text");

                    b.Property<string>("SecondaryText")
                        .HasColumnType("text")
                        .HasColumnName("secondary_text");

                    b.Property<Guid>("WorkspaceAnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_analysis_id");

                    b.HasKey("WorkspaceAnalysisMetricId")
                        .HasName("pk_workspace_analysis_metrics");

                    b.ToTable("workspace_analysis_metrics", "app");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.WorkspaceItem", b =>
                {
                    b.Property<Guid>("WorkspaceItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_item_id");

                    b.Property<string>("GraphEdgeId")
                        .HasColumnType("text")
                        .HasColumnName("graph_edge_id");

                    b.Property<string>("GraphNodeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("graph_node_id");

                    b.Property<string[]>("Labels")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("labels")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<DateTimeOffset>("PinnedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pinned_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("PinnedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("pinned_by");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("WorkspaceItemId")
                        .HasName("pk_workspace_items");

                    b.HasIndex("WorkspaceId", "GraphNodeId", "GraphEdgeId")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_items_workspace_id_graph_node_id_graph_edge_id");

                    b.ToTable("workspace_items", "app");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.WorkspaceMember", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("viewer")
                        .HasColumnName("role");

                    b.HasKey("WorkspaceId", "UserId")
                        .HasName("pk_workspace_members");

                    b.ToTable("workspace_members", "app");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.AITeam", b =>
                {
                    b.HasOne("Geodesic.App.DataLayer.Entities.Workspace", null)
                        .WithOne()
                        .HasForeignKey("Geodesic.App.DataLayer.Entities.AITeam", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_teams_workspaces_workspace_id");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.AITeamMember", b =>
                {
                    b.HasOne("Geodesic.App.DataLayer.Entities.AITeam", "Team")
                        .WithMany("Members")
                        .HasForeignKey("AITeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_team_members_ai_teams_ai_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.SemanticField", b =>
                {
                    b.HasOne("Geodesic.App.DataLayer.Entities.SemanticEntity", "SemanticEntity")
                        .WithMany("Fields")
                        .HasForeignKey("SemanticEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_semantic_fields_semantic_entities_semantic_entity_id");

                    b.Navigation("SemanticEntity");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.AITeam", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Geodesic.App.DataLayer.Entities.SemanticEntity", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
