// <auto-generated />
using Geodesic.App.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Geodesic.App.DataLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251103090000_AddScenarioRunPrompt")]
    partial class AddScenarioRunPrompt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Minimal model snapshot stub. The actual schema shape is defined in AppDbContextModelSnapshot.
            modelBuilder.HasDefaultSchema("app");
        }
    }
}

